import { SearchResult } from "@/lib/embeddings/search";

interface LocalRagContext {
  repoName: string;
  owner: string;
  techStack: any;
  analysis: any;
  readme: string | null;
  extraContext?: string | null;
}

export function generateLocalRagAnswer(
  userQuery: string,
  context: LocalRagContext,
  chunks: SearchResult[]
): string {
  const { repoName, techStack, analysis, readme, extraContext } = context;
  const q = userQuery.toLowerCase().trim();

  // 1. Extra Intelligence Context (Impact / Health)
  if (extraContext && extraContext.trim()) {
    return `${extraContext}\n\n---\n> 💡 *Generated by CodeSphere Intelligence Engine using repository static analysis.*`;
  }

  // 2. High-level Overview / "What does this project do?"
  if (
    /what does this (project|repo|app|codebase|repository) do/i.test(q) ||
    /overview|summary|what is this/i.test(q) ||
    q === "what does this project do?"
  ) {
    const parts: string[] = [];
    parts.push(`### Overview of ${repoName}\n`);

    if (readme) {
      const lines = readme
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith("#") && !l.startsWith("[!") && !l.startsWith("```"));
      if (lines.length > 0) {
        parts.push(lines.slice(0, 3).join(" ") + "\n");
      }
    }

    if (techStack) {
      const langs = techStack.languages?.join(", ") || "Not specified";
      const frameworks = techStack.frameworks?.join(", ") || "None detected";
      parts.push(`**Tech Stack**: Built with **${langs}**${frameworks !== "None detected" ? ` using **${frameworks}**` : ""}.`);
    }

    if (analysis?.entryPoints && Array.isArray(analysis.entryPoints) && analysis.entryPoints.length > 0) {
      const eps = analysis.entryPoints
        .slice(0, 4)
        .map((e: any) => `\`${typeof e === "string" ? e : e.path}\``)
        .join(", ");
      parts.push(`**Primary Entry Points**: ${eps}`);
    }

    if (analysis?.importantDirectories && Array.isArray(analysis.importantDirectories) && analysis.importantDirectories.length > 0) {
      const dirs = analysis.importantDirectories.slice(0, 6).map((d: any) => `\`${d}\``).join(", ");
      parts.push(`**Key Directories**: ${dirs}`);
    }

    if (chunks.length > 0) {
      parts.push("\n### Key Implementation Files:");
      const uniqueFiles = Array.from(new Set(chunks.map((c) => c.filePath))).slice(0, 4);
      for (const f of uniqueFiles) {
        const topChunk = chunks.find((c) => c.filePath === f);
        if (topChunk) {
          parts.push(`- \`${f}\` (lines ${topChunk.startLine}–${topChunk.endLine}): ${topChunk.symbolName ? `implements \`${topChunk.symbolName}\`` : `core ${topChunk.chunkType || "module"} logic`}`);
        }
      }
    }

    parts.push("\n---\n> 💡 *Generated by CodeSphere Local Intelligence. (Configure a valid `GEMINI_API_KEY` in `backend/.env` for cloud LLM synthesis).*");
    return parts.join("\n");
  }

  // 3. Authentication & Security
  if (/auth|login|signup|register|token|jwt|session|password|bcrypt/i.test(q)) {
    const authChunks = chunks.filter((c) =>
      /auth|login|signup|register|token|jwt|session|password|bcrypt/i.test(c.content) ||
      /auth|login|user/i.test(c.filePath)
    );

    const parts: string[] = [];
    parts.push(`### Authentication in ${repoName}\n`);

    if (authChunks.length > 0) {
      parts.push("Authentication and user management implementation was identified across the following components:\n");
      const seen = new Set<string>();
      for (const c of authChunks.slice(0, 4)) {
        if (seen.has(c.filePath)) continue;
        seen.add(c.filePath);
        parts.push(`- \`${c.filePath}\` (lines ${c.startLine}–${c.endLine}): ${c.symbolName ? `defines \`${c.symbolName}\`` : "handles authentication/session flow"}`);
      }

      const sample = authChunks[0];
      parts.push(`\n**Relevant Implementation Snippet** (\`${sample.filePath}\` L${sample.startLine}–${sample.endLine}):`);
      parts.push("```" + (sample.language || "") + "\n" + sample.content.slice(0, 500) + (sample.content.length > 500 ? "\n// ..." : "") + "\n```");
    } else {
      parts.push("No explicit authentication files or tokens were detected in the retrieved code chunks.");
    }

    parts.push("\n---\n> 💡 *Generated by CodeSphere Local Intelligence based on static code search.*");
    return parts.join("\n");
  }

  // 4. Database & Storage
  if (/database|db|model|schema|mongo|postgres|sql|prisma|mongoose/i.test(q)) {
    const dbFiles: string[] = Array.isArray(analysis?.databaseFiles)
      ? analysis.databaseFiles.map((x: any) => (typeof x === "string" ? x : x.path))
      : [];

    const dbChunks = chunks.filter((c) =>
      /db|database|model|schema|query|table|collection/i.test(c.filePath) ||
      /mongoose|prisma|sequelize|knex|pg|mongodb/i.test(c.content)
    );

    const parts: string[] = [];
    parts.push(`### Database & Storage Operations in ${repoName}\n`);

    if (dbFiles.length > 0 || dbChunks.length > 0) {
      const allPaths = Array.from(new Set([...dbFiles, ...dbChunks.map((c) => c.filePath)])).slice(0, 6);
      parts.push("The following files handle database connections, models, or data persistence:\n");
      for (const p of allPaths) {
        const matchingChunk = dbChunks.find((c) => c.filePath === p);
        const lineInfo = matchingChunk ? ` (lines ${matchingChunk.startLine}–${matchingChunk.endLine})` : "";
        parts.push(`- \`${p}\`${lineInfo}`);
      }

      if (dbChunks.length > 0) {
        const sample = dbChunks[0];
        parts.push(`\n**Data Model / Query Snippet** (\`${sample.filePath}\` L${sample.startLine}–${sample.endLine}):`);
        parts.push("```" + (sample.language || "") + "\n" + sample.content.slice(0, 500) + (sample.content.length > 500 ? "\n// ..." : "") + "\n```");
      }
    } else {
      parts.push("No dedicated database schema or ORM files were identified in the primary modules.");
    }

    parts.push("\n---\n> 💡 *Generated by CodeSphere Local Intelligence based on codebase indexing.*");
    return parts.join("\n");
  }

  // 5. API & Routes
  if (/api|endpoint|route|controller|handler/i.test(q)) {
    const apiFiles: string[] = Array.isArray(analysis?.apiFiles)
      ? analysis.apiFiles.map((x: any) => (typeof x === "string" ? x : x.path))
      : [];

    const apiChunks = chunks.filter((c) =>
      /api|route|controller/i.test(c.filePath) ||
      /(app|router)\.(get|post|put|delete|patch)/i.test(c.content)
    );

    const parts: string[] = [];
    parts.push(`### API Endpoints and Routing in ${repoName}\n`);

    if (apiFiles.length > 0 || apiChunks.length > 0) {
      const allPaths = Array.from(new Set([...apiFiles, ...apiChunks.map((c) => c.filePath)])).slice(0, 6);
      parts.push("API definitions and request routing are implemented in:\n");
      for (const p of allPaths) {
        const matching = apiChunks.find((c) => c.filePath === p);
        const lineInfo = matching ? ` (lines ${matching.startLine}–${matching.endLine})` : "";
        parts.push(`- \`${p}\`${lineInfo}`);
      }

      if (apiChunks.length > 0) {
        const sample = apiChunks[0];
        parts.push(`\n**Route Definition Example** (\`${sample.filePath}\` L${sample.startLine}–${sample.endLine}):`);
        parts.push("```" + (sample.language || "") + "\n" + sample.content.slice(0, 500) + (sample.content.length > 500 ? "\n// ..." : "") + "\n```");
      }
    } else {
      parts.push("No dedicated API routes were detected for this question.");
    }

    parts.push("\n---\n> 💡 *Generated by CodeSphere Local Intelligence.*");
    return parts.join("\n");
  }

  // 6. Architecture & Dependency Flow
  if (/depend|architecture|connect|flow|structure|module/i.test(q)) {
    const parts: string[] = [];
    parts.push(`### Architecture & Dependencies for ${repoName}\n`);

    if (analysis?.entryPoints && Array.isArray(analysis.entryPoints) && analysis.entryPoints.length > 0) {
      const eps = analysis.entryPoints.slice(0, 4).map((e: any) => `\`${typeof e === "string" ? e : e.path}\``).join(", ");
      parts.push(`**Execution Entry Points**: ${eps}`);
    }

    if (analysis?.importantModules && Array.isArray(analysis.importantModules) && analysis.importantModules.length > 0) {
      const mods = analysis.importantModules.slice(0, 5).map((m: any) => `\`${typeof m === "string" ? m : m.path}\``).join(", ");
      parts.push(`**Central Modules**: ${mods}`);
    }

    if (chunks.length > 0) {
      parts.push("\n**Relevant Code Modules**:");
      const unique = Array.from(new Set(chunks.map((c) => c.filePath))).slice(0, 4);
      for (const u of unique) {
        const c = chunks.find((x) => x.filePath === u);
        if (c) {
          parts.push(`- \`${u}\` (lines ${c.startLine}–${c.endLine}): ${c.symbolName ? `Symbol \`${c.symbolName}\`` : `${c.chunkType} chunk`}`);
        }
      }
    }

    parts.push("\n---\n> 💡 *Generated by CodeSphere Local Intelligence.*");
    return parts.join("\n");
  }

  // 7. General question with retrieved chunks
  if (chunks.length > 0) {
    const parts: string[] = [];
    parts.push(`Based on code analysis of **${repoName}**, here are the most relevant implementation details:\n`);

    const topChunks = chunks.slice(0, 3);
    for (const c of topChunks) {
      parts.push(`#### \`${c.filePath}\` (Lines ${c.startLine}–${c.endLine})`);
      if (c.symbolName) {
        parts.push(`**Symbol**: \`${c.symbolName}\` (${c.chunkType})`);
      }
      parts.push("```" + (c.language || "") + "\n" + c.content.slice(0, 600) + (c.content.length > 600 ? "\n// ..." : "") + "\n```\n");
    }

    parts.push("---\n> 💡 *Generated by CodeSphere Local Intelligence using direct source chunk retrieval.*");
    return parts.join("\n");
  }

  // 8. Fallback if no chunks matched
  return `I analyzed the repository for **"${userQuery}"**, but could not find matching code chunks. You can review the repository entry points in the Graph tab or generate project documentation in the Documentation tab.\n\n---\n> 💡 *Generated by CodeSphere Local Intelligence.*`;
}
